### ISSUE TITLE
find order(created_at: ...) is not possible?

### ISSUE THREAD

**Issue by gfx** [soutaro/querly#19]
In most of Rails projects, `order(id: ...)` is better than `order(created_at: ...)` so I'd like to add rules about it; however `find order(created_at: ...)` raises errors as follows.

In console:

```
> find order(created_at: ...)
Error:
parse error on value "..." (DOTDOTDOT)
```

**Comment by pocke** [comment]
I guess `order(created_at: _)` or `order(created_at: _, ...)`are enough for the purpose. WDYT?

**Comment by gfx** [comment]
It's not a question. Just a bug report. If it is intended behavior, querly should report more readable error messages, I guess.

**Comment by soutaro** [comment]
This is an intended behavior. You can write `order(created_at: _, ...)`.

I agree that there can be a better error message, but still I have no plan to improve that. Generally, error message generation for syntax errors by auto-generated parser is difficult, and almost an open problem. (Are you talking about this? @gfx )
