### ISSUE TITLE
New ruby syntax support

### ISSUE THREAD

**Issue by nulldef** [soutaro/querly#78]
Hi there,

I'm trying to use querly with a project on ruby 2.7 and it causes a couple of errors like 
```sh
#<Parser::SyntaxError: unexpected token tDOT3>
#<Parser::SyntaxError: unexpected token tRBRACK>
```

It seems to be a problem of using `Parser::Ruby25` class instead of `Parser::CurrentRuby`.

**Comment by ybiquitous** [comment]
I can reproduce the error by the following steps.
This test Ruby script uses the **Endless Range** feature since Ruby 2.6 (see also the [official announce](https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/)):

```console
$ cat foo.rb
pp (1...)

$ cat querly.yaml
rules:
  - id: foo
    pattern: foo
    message: Disallow `foo` method

$ querly check foo.rb
Failed to load script: foo.rb
#<Parser::SyntaxError: unexpected token tRPAREN>
```

My environment:

```console
$ querly version
Querly 1.1.0

$ ruby --version
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
```

---

I agree with the following comment by @nulldef,

> It seems to be a problem of using Parser::Ruby25 class instead of Parser::CurrentRuby.

but are there any barriers to tackle this problem? 🤔 
If no barriers, I'm ready to open a new pull request.

**Comment by satoruk** [comment]
@ybiquitous 

> but are there any barriers to tackle this problem? 🤔

I’m facing the same issue too.

I think it's afraid that some versions of Ruby cannot be guaranteed by testing.
So that's why they seem to be avoiding `Parser::CurrentRuby` I think.

**Comment by soutaro** [comment]
I'm sorry. I'm currently using most of my time for RBS and Steep. It would be great if you can write a patch to run Querly with Ruby 2.7 and 3.0.

**Comment by ybiquitous** [comment]
@soutaro I will write a patch. 💪 

Do you mean that we will update the gemspec to set `spec.required_ruby_version = ">= 2.7"`?
(the [current gemspec](https://github.com/soutaro/querly/blob/e88fc6d60c71bd6deca6774941406761e1718f5a/querly.gemspec) does not have `required_ruby_version`, though)

**Comment by soutaro** [comment]
@ybiquitous I'm good for adding `required_ruby_version`. 2.7 would be reasonable.

**Comment by ybiquitous** [comment]
Hi, I've opened PR #88 that should resolve this issue.
